package main

import (
	"fmt"

	"github.com/signintech/gopdf"
)

func main() {
	pdf := gopdf.GoPdf{}
	pdf.Start(gopdf.Config{
		PageSize: gopdf.Rect{W: 595.28, H: 841.89}, // A4, portrait
	})
	pdf.AddPage()
	err := pdf.AddTTFFont("NotoSans", "assets/ttf/NotoSans-Regular.ttf")
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	err = pdf.SetFont("NotoSans", "", 14)
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	pdf.Cell(nil, "PDF file generated by Invoicer")
	pdf.WritePdf("out.pdf")
}
